services:
  - type: web
    name: uma-portfolio
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
